### PR TITLE
fix: issue with publish ignoring 'drain' event. 

### PR DESCRIPTION
**Pull request by richardklafter**
This PR addresses issue #129. 

There didn't seem to be a good way to test it within the testing framework in the repository so I wrote a small repo script.

```js
var amqp = require('./lib/index');
async function main() {
  var connection = amqp.connect(['amqp://guest:guest@localhost']);
  var channelWrapper = connection.createChannel({
    setup: function (channel) {
      return channel.assertQueue('rxQueueName', { durable: true });
    }
  });


  //this way works fine
  console.log('starting serial queueing...')
  for (let i = 0; i < 200000; i++) {
    await channelWrapper.sendToQueue('rxQueueName', Buffer.from('serial'+i))
  }
  console.log(`finished serial queueing`)

  //this way fails because is ignores drain
  console.log('starting parallel queueing')
  const promises = []
  for (let i = 0; i < 200000; i++) {
    promises.push(channelWrapper.sendToQueue('rxQueueName', Buffer.from('parallel'+i)))
  }
  setTimeout(()=>{
    console.error('It has been 10 mins. Good chance your promises are never coming back :(')
  }, 1000*60*10)
  await Promise.all(promises)
  console.log(`finished parallel queueing`)
}
main().then(()=>console.log('Done testing!')).catch(console.error).then(()=>process.exit())
``` 

Output before this PR:
```
Successfully compiled 4 files with Babel (520ms).
Done in 0.65s.
starting serial queueing...
finished serial queueing
starting parallel queueing
It has been 10 mins. Good chance your promises are never coming back :(
```

Output after this PR:
```
Successfully compiled 4 files with Babel (416ms).
Done in 0.52s.
starting serial queueing...
finished serial queueing
starting parallel queueing
finished parallel queueing
Done testing!
```

### CODE REVIEW

**Comment by jwalton** [comment]
Thanks so much for this!  One small request - can you change your commit message to something like:

```
fix: fixed issue with publish ignoring 'drain' event

fix #129
```

?  This uses semantic-release, so the commit message has to follow that format for the release notes to be generated correctly.  I can fix it with a squash merge, but then you won't show up as a "contributor" in github, and some people are touchy about that.  ;)

> Good chance your promises are never coming back

Hahaha

**Review by jwalton — APPROVED** [review]

**Comment by richardklafter** [comment]
Updated commit message. If it is still wrong feel free to squash merge. Thanks!

**Comment by jwalton** [comment]
Thanks again!

**Comment by jwalton** [comment]
Unit tests are failing (Why didn't github actions run on this PR?  -_-)  I'll see if I can have a look tonight.

**Pull request merged**
